name: Running on demand automation API

on:
  workflow_dispatch:
    inputs:
      logLevel:
      tags:
        description: 'Input tag scenario'
        required: true
        default: smoke-test
        
jobs:
 run-automation:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.2.1
      with:
        java-version: 11
    - name: Running API
      run:  mvn clean test -D"cucumber.filter.tags=@${{ inputs.tags }}"
    - name: Publish Test Report
      uses: scacap/action-surefire-report@v1
    
